babasport/src/cn/itcast/bean/BuyCart.java
package cn.itcast.bean;

import java.util.ArrayList;
import java.util.List;

import cn.itcast.bean.book.OrderContactInfo;
import cn.itcast.bean.book.OrderDeliverInfo;
import cn.itcast.bean.book.PaymentWay;

/**
 * 购物车
 */
public class BuyCart {
	/* 购物项 */
	private List<BuyItem> items = new ArrayList<BuyItem>();
	/* 配送信息 */
	private OrderDeliverInfo deliverInfo;
	/* 购买者联系信息 */
	private OrderContactInfo contactInfo;
	/* 支付方式 */
	private PaymentWay paymentWay;
	/* 购买者与收货人是否相同 */
	private Boolean buyerIsrecipients;
	/* 配送费 */
	private float deliveFee = 10f;
	/* 附言 */
	private String note;
	
	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public float getDeliveFee() {
		return deliveFee;
	}

	public void setDeliveFee(float deliveFee) {
		this.deliveFee = deliveFee;
	}

	public PaymentWay getPaymentWay() {
		return paymentWay;
	}

	public void setPaymentWay(PaymentWay paymentWay) {
		this.paymentWay = paymentWay;
	}

	public Boolean getBuyerIsrecipients() {
		return buyerIsrecipients;
	}

	public void setBuyerIsrecipients(Boolean buyerIsrecipients) {
		this.buyerIsrecipients = buyerIsrecipients;
	}

	public OrderContactInfo getContactInfo() {
		return contactInfo;
	}

	public void setContactInfo(OrderContactInfo contactInfo) {
		this.contactInfo = contactInfo;
	}

	public OrderDeliverInfo getDeliverInfo() {
		return deliverInfo;
	}

	public void setDeliverInfo(OrderDeliverInfo deliverInfo) {
		this.deliverInfo = deliverInfo;
	}

	public List<BuyItem> getItems() {
		return items;
	}

	/**
	 * 添加购物项
	 * @param item 购物项
	 */
	public void add(BuyItem item){
		if(this.items.contains(item)){
			for(BuyItem it : this.items){
				if(it.equals(item)){
					it.setAmount(it.getAmount()+1);
					break;
				}
			}
		}else{
			this.items.add(item);
		}
	}
	/**
	 * 删除指定购物项
	 * @param item 购物项
	 */
	public void delete(BuyItem item){
		if(this.items.contains(item)) this.items.remove(item);
	}
	/**
	 * 清空购物项
	 */
	public void deleteAll(){
		this.items.clear();
	}
	
	/**
	 * 计算商品总销售价
	 * @return
	 */
	public float getTotalSellPrice(){
		float totalprice = 0F;
		for(BuyItem item : this.items){
			totalprice += item.getProduct().getSellprice() * item.getAmount();
		}
		return totalprice;
	}
	/**
	 * 计算商品总市场价
	 * @return
	 */
	public float getTotalMarketPrice(){
		float totalprice = 0F;
		for(BuyItem item : this.items){
			totalprice += item.getProduct().getMarketprice() * item.getAmount();
		}
		return totalprice;
	}
	/**
	 * 计算总节省金额
	 * @return
	 */
	public float getTotalSavedPrice(){
		return this.getTotalMarketPrice() - this.getTotalSellPrice();
	}
	/**
	 * 计算订单的总费用
	 * @return
	 */
	public float getOrderTotalPrice(){
		return this.getTotalSellPrice()+ this.deliveFee;
	}
}

babasport/src/cn/itcast/bean/book/PaymentWay.java
package cn.itcast.bean.book;
/**
 * 支付方式
 */
public enum PaymentWay {
	NET{
		public String getName(){
			return "网上支付";
		}
	},
	COD{
		public String getName(){
			return "货到付款";
		}
	},
	BANKREMITTANCE{
		public String getName(){
			return "银行电汇";
		}
	},
	POSTOFFICEREMITTANCE{
		public String getName(){
			return "邮局汇款";
		}
	};
	public abstract String getName();
}

babasport/src/cn/itcast/bean/product/ProductInfo.java
package cn.itcast.bean.product;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.compass.annotations.Index;
import org.compass.annotations.Searchable;
import org.compass.annotations.SearchableComponent;
import org.compass.annotations.SearchableId;
import org.compass.annotations.SearchableProperty;
import org.compass.annotations.Store;

@Entity @Searchable //通过这个注解,指明该类跟lucene中的document映射
public class ProductInfo implements Serializable{
	private static final long serialVersionUID = -8860864584425256200L;
	private Integer id;
	/** 货号 **/
	private String code;
	/** 产品名称 **/
	private String name;
	/** 品牌 **/
	private Brand brand;
	/** 型号 **/
	private String model;
	/** 底价(采购进来的价格) **/
	private Float baseprice;
	/** 市场价 **/
	private Float marketprice;
	/** 销售价 **/
	private Float sellprice;
	/** 重量 单位:克 **/
	private Integer weight;
	/** 产品简介 **/
	private String description;
	/** 购买说明 **/
	private String buyexplain;
	/** 是否可见 **/
	private Boolean visible = true;
	/** 产品类型 **/
	private ProductType type;
	/** 上架日期 **/
	private Date createdate = new Date();
	/** 人气指数 **/
	private Integer clickcount = 1;
	/** 销售量 **/
	private Integer sellcount = 0;
	/** 是否推荐 **/
	private Boolean commend = false;
	/** 性别要求 **/
	private Sex sexrequest = Sex.NONE;
	/** 产品样式 **/
	private Set<ProductStyle> styles = new HashSet<ProductStyle>();
	
	public ProductInfo(Integer id) {
		this.id = id;
	}
	public ProductInfo() {}
	
	@Transient
	public Float getSavedPrice(){
		return marketprice-sellprice;
	}
	
	@OneToMany(cascade={CascadeType.REMOVE,CascadeType.PERSIST}, mappedBy="product")
	@OrderBy("visible desc, id asc") @SearchableComponent
	public Set<ProductStyle> getStyles() {
		return styles;
	}
	public void setStyles(Set<ProductStyle> styles) {
		this.styles = styles;
	}
	/**
	 * 从样式集合中删除指定样式
	 * @param style
	 */
	public void removeProductStyle(ProductStyle style){
		if(this.styles.contains(style)){
			this.styles.remove(style);
			style.setProduct(null);
		}
	}	
	/**
	 * 添加样式到样式集合
	 * @param style
	 */
	public void addProductStyle(ProductStyle style){
		if(!this.styles.contains(style)){
			this.styles.add(style);
			style.setProduct(this);
		}
	}
	
	@Id @GeneratedValue @SearchableId
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	@Column(length=30) @SearchableProperty(index=Index.NO,store=Store.YES)
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	@Column(length=50,nullable=false) @SearchableProperty(boost=2,store=Store.YES, name="productName")
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	@ManyToOne(cascade=CascadeType.REFRESH)
	@JoinColumn(name="brandid") @SearchableComponent
	public Brand getBrand() {
		return brand;
	}
	public void setBrand(Brand brand) {
		this.brand = brand;
	}
	@Column(length=20) @SearchableProperty(index=Index.NO,store=Store.YES)
	public String getModel() {
		return model;
	}
	public void setModel(String model) {
		this.model = model;
	}
	@Column(nullable=false)
	public Float getBaseprice() {
		return baseprice;
	}
	public void setBaseprice(Float baseprice) {
		this.baseprice = baseprice;
	}
	@Column(nullable=false) @SearchableProperty(index=Index.NO,store=Store.YES)
	public Float getMarketprice() {
		return marketprice;
	}
	public void setMarketprice(Float marketprice) {
		this.marketprice = marketprice;
	}
	@Column(nullable=false) @SearchableProperty(index=Index.NO,store=Store.YES)
	public Float getSellprice() {
		return sellprice;
	}
	public void setSellprice(Float sellprice) {
		this.sellprice = sellprice;
	}
	@SearchableProperty(index=Index.NO,store=Store.YES)
	public Integer getWeight() {
		return weight;
	}
	public void setWeight(Integer weight) {
		this.weight = weight;
	}
	@Lob @Column(nullable=false) @SearchableProperty(store=Store.YES)
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	@Column(length=30) @SearchableProperty(index=Index.NO,store=Store.YES)
	public String getBuyexplain() {
		return buyexplain;
	}
	public void setBuyexplain(String buyexplain) {
		this.buyexplain = buyexplain;
	}
	@Column(nullable=false)
	public Boolean getVisible() {
		return visible;
	}
	public void setVisible(Boolean visible) {
		this.visible = visible;
	}
	@ManyToOne(cascade=CascadeType.REFRESH,optional=false)
	@JoinColumn(name="typeid") @SearchableComponent
	public ProductType getType() {
		return type;
	}
	public void setType(ProductType type) {
		this.type = type;
	}
	@Temporal(TemporalType.DATE) @SearchableProperty(index=Index.NO,store=Store.YES,format="yyyy-MM-dd")
	public Date getCreatedate() {
		return createdate;
	}
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}
	@Column(nullable=false)
	public Integer getClickcount() {
		return clickcount;
	}
	public void setClickcount(Integer clickcount) {
		this.clickcount = clickcount;
	}
	@Column(nullable=false)
	public Integer getSellcount() {
		return sellcount;
	}
	public void setSellcount(Integer sellcount) {
		this.sellcount = sellcount;
	}
	@Column(nullable=false)
	public Boolean getCommend() {
		return commend;
	}
	public void setCommend(Boolean commend) {
		this.commend = commend;
	}
	@Enumerated(EnumType.STRING) @Column(length=5,nullable=false) @SearchableProperty(index=Index.NO,store=Store.YES)
	public Sex getSexrequest() {
		return sexrequest;
	}
	public void setSexrequest(Sex sexrequest) {
		this.sexrequest = sexrequest;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final ProductInfo other = (ProductInfo) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
}

babasport/src/cn/itcast/web/action/shopping/BuyCartManageAction.java
package cn.itcast.web.action.shopping;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.springframework.stereotype.Controller;

import cn.itcast.bean.BuyCart;
import cn.itcast.bean.BuyItem;
import cn.itcast.bean.product.ProductInfo;
import cn.itcast.bean.product.ProductStyle;
import cn.itcast.utils.WebUtil;
import cn.itcast.web.formbean.shopping.BuyCartForm;

@Controller("/shopping/cart/manage")
public class BuyCartManageAction extends DispatchAction {
	
	/**
	 * 删除指定购物项
	 */
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		BuyCart cart = (BuyCart)WebUtil.getBuyCart(request);
		BuyCartForm formbean = (BuyCartForm) form;
		if(formbean.getProductid()!=null && formbean.getProductid()>0
				&& formbean.getStyleid()!=null && formbean.getStyleid()>0){
			ProductInfo product = new ProductInfo(formbean.getProductid());
			product.addProductStyle(new ProductStyle(formbean.getStyleid()));
			BuyItem item = new BuyItem(product);
			cart.delete(item);
		}
		request.setAttribute("directUrl", "/shopping/cart.do");
		return mapping.findForward("directUrl");
	}
	/**
	 * 清空购物车
	 */
	public ActionForward deleteAll(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		BuyCart cart = (BuyCart)WebUtil.getBuyCart(request);
		cart.deleteAll();
		request.setAttribute("directUrl", "/shopping/cart.do");
		return mapping.findForward("directUrl");
	}
	/**
	 * 修改购买数量
	 */
	public ActionForward updateAmount(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		modifyBuyAmount(request);
		request.setAttribute("directUrl", "/shopping/cart.do");
		return mapping.findForward("directUrl");
	}
	
	private void modifyBuyAmount(HttpServletRequest request) {
		BuyCart cart = (BuyCart)WebUtil.getBuyCart(request);
		for(BuyItem item : cart.getItems()){
			StringBuilder sb = new StringBuilder("amount_");
			sb.append(item.getProduct().getId()).append("_");
			sb.append(item.getProduct().getStyles().iterator().next().getId());
			String amount = request.getParameter(sb.toString());
			if(amount!=null && !"".equals(amount.trim())){
				item.setAmount(new Integer(amount.trim()));
			}
		}
	}
	/**
	 * 结算
	 */
	public ActionForward settleAccounts(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		modifyBuyAmount(request);
		BuyCartForm formbean = (BuyCartForm) form;
		String url = "/customer/shopping/deliver.do";
		if(formbean.getDirectUrl()!=null && !"".equals(formbean.getDirectUrl())) url = formbean.getDirectUrl();
		request.setAttribute("directUrl", url);
		return mapping.findForward("directUrl");
	}
	
	
}

babasport/src/cn/itcast/web/action/shopping/DeliverInfoAction.java
package cn.itcast.web.action.shopping;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.stereotype.Controller;

import cn.itcast.bean.BuyCart;
import cn.itcast.bean.user.Buyer;
import cn.itcast.bean.user.Gender;
import cn.itcast.utils.WebUtil;
import cn.itcast.web.formbean.shopping.DeliverForm;

@Controller("/customer/shopping/deliver")
public class DeliverInfoAction extends Action {

	@Override
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		DeliverForm formbean = (DeliverForm) form;
		formbean.setGender(Gender.MAN);
		formbean.setBuyer_gender(Gender.MAN);
		formbean.setBuyerIsrecipients(true);
		BuyCart cart = WebUtil.getBuyCart(request);
		if(cart.getDeliverInfo()!=null){
			formbean.setRecipients(cart.getDeliverInfo().getRecipients());
			formbean.setAddress(cart.getDeliverInfo().getAddress());
			formbean.setEmail(cart.getDeliverInfo().getEmail());
			formbean.setGender(cart.getDeliverInfo().getGender());
			formbean.setMobile(cart.getDeliverInfo().getMobile());
			formbean.setPostalcode(cart.getDeliverInfo().getPostalcode());
			formbean.setTel(cart.getDeliverInfo().getTel());
			formbean.setBuyerIsrecipients(cart.getBuyerIsrecipients());
		}else{
			//当购物车里没有购买者的联系信息时,将用户的个人联系信息作为默认数据显示在收货人信息输入字段上
			Buyer buyer = WebUtil.getBuyer(request);
			if(buyer.getContactInfo()!=null){
				formbean.setRecipients(buyer.getRealname());
				formbean.setAddress(buyer.getContactInfo().getAddress());
				formbean.setEmail(buyer.getEmail());
				formbean.setGender(buyer.getGender());
				formbean.setMobile(buyer.getContactInfo().getMobile());
				formbean.setPostalcode(buyer.getContactInfo().getPostalcode());
				formbean.setTel(buyer.getContactInfo().getPhone());
				formbean.setBuyerIsrecipients(true);
			}
		}
		if(cart.getContactInfo()!=null){
			formbean.setBuyer(cart.getContactInfo().getBuyerName());
			formbean.setBuyer_address(cart.getContactInfo().getAddress());
			formbean.setBuyer_gender(cart.getContactInfo().getGender());
			formbean.setBuyer_mobile(cart.getContactInfo().getMobile());
			formbean.setBuyer_postalcode(cart.getContactInfo().getPostalcode());
			formbean.setBuyer_tel(cart.getContactInfo().getTel());
		}else{
			//当购物车里没有购买者的联系信息时,将用户的个人联系信息作为默认数据显示在购买人信息输入字段上
			Buyer buyer = WebUtil.getBuyer(request);
			if(buyer.getContactInfo()!=null){
				formbean.setBuyer(buyer.getRealname());
				formbean.setBuyer_address(buyer.getContactInfo().getAddress());
				formbean.setBuyer_gender(buyer.getGender());
				formbean.setBuyer_mobile(buyer.getContactInfo().getMobile());
				formbean.setBuyer_postalcode(buyer.getContactInfo().getPostalcode());
				formbean.setBuyer_tel(buyer.getContactInfo().getPhone());
			}
		}
		return mapping.findForward("deliverInfo");
	}

}

babasport/WebRoot/WEB-INF/page/shopping/cart.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/WEB-INF/page/share/taglib.jsp" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<HEAD>
<TITLE>购物车 巴巴运动网</TITLE>
<META http-equiv=Content-Type content="text/html; charset=UTF-8">
<META http-equiv=Content-Language content=zh-CN>
<LINK href="/css/new_cart.css" rel="stylesheet" type="text/css">
<link href="/css/global/header01.css" rel="stylesheet" type="text/css">
<SCRIPT language=JavaScript src="/js/FoshanRen.js"></SCRIPT>
<SCRIPT LANGUAGE="JavaScript">
<!--
/** 获取以指定字符串为前缀的输入字段集合 **/
/** 数字输入格式是否正确(长度1-4位，第一个数字必须是1-9) **/
function numericFormat(strNumber){   
  var newPar=/^[1-9]\d{0,3}$/;
  return newPar.test(strNumber);
} 

function getInputsByname(name, etype){//
	var inputs = document.getElementsByTagName("input");
	var texts = new Array();
	var y = 0;
	for (var i = 0; i < inputs.length; i++) {
	  if (inputs[i].type == etype && inputs[i].name!=null && inputs[i].name.substring(0, name.length) == name) {
			texts[y] = inputs[i];
			y++;
		}
	}
	return texts;
}
function settleAccounts(){
	if(validateAmount()){		
		var form = document.forms["buycart"];
		form.method.value="settleAccounts";
		form.submit();
	}
}

function modifyAmount(){
	if(validateAmount()){		
		var form = document.forms["buycart"];
		form.method.value="updateAmount";
		form.submit();
	}
}

/** 验证购买数量字段 **/
function validateAmount(){
	var amounts = getInputsByname("amount_", "text");
	if(amounts.length==0){
		alert("您还没有购买商品");
		return false;
	}else{
		for (var i = 0; i < amounts.length; i++) {
			var amount = amounts[i];
			if(amount.value==null || amount.value.trim()==""){
				alert("\n您购买的商品中,有的商品购买数量为空,请填写购买数量");
				amount.focus();
				return false;
			}else if(amount.value=="0"){
				alert("\n您购买的商品中,有的商品购买数量为0,如果您不需要该商品,可以删除它");
				amount.select();
				return false;
			}else if(!numericFormat(amount.value)){
				alert("\n购买数量含有非数字数据,请更正");
				amount.select();
				return false;
			}
		}
	}
	return true;
}
//-->
</SCRIPT>
</HEAD>
<BODY>
<jsp:include page="/WEB-INF/page/share/Head.jsp"/>
<BR>
<TABLE cellSpacing=0 cellPadding=5 width="98%" border="0" align="center">
  <TR>
    <TD><TABLE cellSpacing=0 cellPadding=0 width="96%" border=0>
      <TBODY>
        <TR>
          <TD width="24%"><IMG height=31 src="/images/buy/shop-cart-header-blue.gif" width="218" border=0></TD>
          <TD width="34%">如果您修改了商品数量，请点击 
             <img style="CURSOR: hand; " alt="修改数量" src="/images/buy/update-t-sm.gif" value="修改数量" border="0" onClick="javascript:modifyAmount()"></TD>
          <TD width="14%" align="left"><a href="<html:rewrite action="/shopping/cart/manage" />?method=deleteAll&directUrl=${param.directUrl}"><img style="CURSOR:hand;" alt="清空购物车" src="/images/buy/az-empty-shoppingcard.gif" border="0"></a></TD>
          <TD width="15%" align=left><a href="/"><img src="/images/buy/as-s-continus.gif" width="116" height="22" border="0"></a></TD>
          <TD width="13%" align=right><img style="CURSOR:hand;" src="/images/buy/az-by-split.gif" width="116" height="22" onClick="javascript:settleAccounts()"></TD>
        </TR>
      </TBODY>
    </TABLE></TD>
  </TR>

  <TR>
    <TD><FORM id="buycart" name="buycart" action="<html:rewrite action="/shopping/cart/manage" />" method="post">
    <INPUT TYPE="hidden" NAME="method" value="">
     <INPUT TYPE="hidden" NAME="directUrl" value="${param.directUrl}">
    <TABLE cellSpacing=0 cellPadding=6 width="100%" border=0> 
      <TR bgColor=#d7ebff>
        <TD width="457"><STRONG>我的购物车里的商品--马上购买</STRONG></TD>
        <TD width=112><DIV align=center><STRONG>市场价</STRONG></DIV></TD>
        <TD width=181><DIV align=center><STRONG>价格</STRONG></DIV></TD>
        <TD width=73><DIV align=center><STRONG>数量</STRONG></DIV></TD>
        <TD width=66>&nbsp;</TD>
      </TR>
<!-- loop begin -->
<c:forEach items="${buyCart.items}" var="item"> 
       <TR vAlign="top">
        <TD><STRONG><A href="" target="_blank">${item.product.name}</A></STRONG> <span class="h3color">[颜色/样式：<c:forEach items="${item.product.styles}" var="style">${style.name}</c:forEach>]</span><BR><BR></TD>
        <TD width="112" align="center"><SPAN class="price" title="￥${item.product.marketprice}元"><FONT color="black"><S><B>￥${item.product.marketprice}元</B></S></FONT></SPAN></TD>
        <TD width="181"><P align="center"><SPAN class="price"><B>￥${item.product.sellprice} 元</B></SPAN> <BR>
          为您节省：<SPAN class=price>￥${item.product.savedPrice}元 </SPAN><BR> </P></TD>
        <TD align="middle" width="73"><INPUT type="text" style="WIDTH: 30px" maxLength="3" value="${item.amount}"  name="amount_${item.product.id}_<c:forEach items="${item.product.styles}" var="style">${style.id}</c:forEach>" onkeypress="javascript:InputIntNumberCheck()"></TD>
        <TD align="middle" width="66"><a href="<html:rewrite action="/shopping/cart/manage" />?method=delete&directUrl=${param.directUrl }&buyitemid=${item.product.id}-<c:forEach items="${item.product.styles}" var="style">${style.id}</c:forEach>"><img height="17" src="/images/buy/delete.gif" width="45" border="0"></a></TD>
      </TR>
      <TR vAlign="top">
        <TD colSpan="5"><IMG height=1 src="/images/buy/green-pixel.gif" width="100%" border="0"></TD>
      </TR>
</c:forEach>
<!-- loop end -->	  
    </TABLE></FORM>
      <table width="96%" border="0" align="left">
        <tr>
          <td width="60%" align="right">如果您修改了商品数量，请点击
          <img style="CURSOR:hand;" alt="修改数量" src="/images/buy/update-t-sm.gif" value="修改数量" border="0" onClick="javascript:modifyAmount()"></td>
          <td width="9%" align="right"><DIV align="right"><SPAN class="price"><STRONG><B><FONT color="black">共计:</FONT></B></STRONG></SPAN></DIV></td>
          <td width="11%" align="right"><DIV align="center"><SPAN class="price"><STRONG><B class="price"><FONT color="black">${buyCart.totalSellPrice }元</FONT></B></STRONG></SPAN></DIV></td>
          <td width="8%" align="right"><DIV align="right"><SPAN class="price"><STRONG><B><FONT color="black">节省:</FONT></B></STRONG></SPAN></DIV></td>
          <td width="12%" align="right"><DIV align="center"><SPAN class="price"><STRONG><B class="price">${buyCart.totalSavedPrice }元</B></STRONG></SPAN></DIV></td>
        </tr>
        <tr>
          <td colspan="3" align="right">&nbsp;</td>
          <td colspan="2" align="right"><img style="CURSOR:hand;" src="/images/buy/az-by-split.gif" width="116" height="22" onClick="javascript:settleAccounts()"></td>
        </tr>
      </table></TD>
  </TR>
</TABLE>
<br>
<jsp:include page="/WEB-INF/page/share/Foot.jsp" />
</BODY>
</HTML>