babasport/src/cn/itcast/bean/product/ProductInfo.java
package cn.itcast.bean.product;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.compass.annotations.Index;
import org.compass.annotations.Searchable;
import org.compass.annotations.SearchableComponent;
import org.compass.annotations.SearchableId;
import org.compass.annotations.SearchableProperty;
import org.compass.annotations.Store;

@Entity @Searchable //通过这个注解,指明该类跟lucene中的document映射
public class ProductInfo implements Serializable{
	private static final long serialVersionUID = -8860864584425256200L;
	private Integer id;
	/** 货号 **/
	private String code;
	/** 产品名称 **/
	private String name;
	/** 品牌 **/
	private Brand brand;
	/** 型号 **/
	private String model;
	/** 底价(采购进来的价格) **/
	private Float baseprice;
	/** 市场价 **/
	private Float marketprice;
	/** 销售价 **/
	private Float sellprice;
	/** 重量 单位:克 **/
	private Integer weight;
	/** 产品简介 **/
	private String description;
	/** 购买说明 **/
	private String buyexplain;
	/** 是否可见 **/
	private Boolean visible = true;
	/** 产品类型 **/
	private ProductType type;
	/** 上架日期 **/
	private Date createdate = new Date();
	/** 人气指数 **/
	private Integer clickcount = 1;
	/** 销售量 **/
	private Integer sellcount = 0;
	/** 是否推荐 **/
	private Boolean commend = false;
	/** 性别要求 **/
	private Sex sexrequest = Sex.NONE;
	/** 产品样式 **/
	private Set<ProductStyle> styles = new HashSet<ProductStyle>();
	
	public ProductInfo(Integer id) {
		this.id = id;
	}
	public ProductInfo() {}
	
	@Transient
	public Float getSavedPrice(){
		return marketprice-sellprice;
	}
	
	@OneToMany(cascade={CascadeType.REMOVE,CascadeType.PERSIST}, mappedBy="product")
	@OrderBy("visible desc, id asc") @SearchableComponent
	public Set<ProductStyle> getStyles() {
		return styles;
	}
	public void setStyles(Set<ProductStyle> styles) {
		this.styles = styles;
	}
	/**
	 * 从样式集合中删除指定样式
	 * @param style
	 */
	public void removeProductStyle(ProductStyle style){
		if(this.styles.contains(style)){
			this.styles.remove(style);
			style.setProduct(null);
		}
	}	
	/**
	 * 添加样式到样式集合
	 * @param style
	 */
	public void addProductStyle(ProductStyle style){
		if(!this.styles.contains(style)){
			this.styles.add(style);
			style.setProduct(this);
		}
	}
	
	@Id @GeneratedValue @SearchableId
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	@Column(length=30) @SearchableProperty(index=Index.NO,store=Store.YES)
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	@Column(length=50,nullable=false) @SearchableProperty(boost=2,store=Store.YES, name="productName")
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	@ManyToOne(cascade=CascadeType.REFRESH)
	@JoinColumn(name="brandid") @SearchableComponent
	public Brand getBrand() {
		return brand;
	}
	public void setBrand(Brand brand) {
		this.brand = brand;
	}
	@Column(length=20) @SearchableProperty(index=Index.NO,store=Store.YES)
	public String getModel() {
		return model;
	}
	public void setModel(String model) {
		this.model = model;
	}
	@Column(nullable=false)
	public Float getBaseprice() {
		return baseprice;
	}
	public void setBaseprice(Float baseprice) {
		this.baseprice = baseprice;
	}
	@Column(nullable=false) @SearchableProperty(index=Index.NO,store=Store.YES)
	public Float getMarketprice() {
		return marketprice;
	}
	public void setMarketprice(Float marketprice) {
		this.marketprice = marketprice;
	}
	@Column(nullable=false) @SearchableProperty(index=Index.NO,store=Store.YES)
	public Float getSellprice() {
		return sellprice;
	}
	public void setSellprice(Float sellprice) {
		this.sellprice = sellprice;
	}
	@SearchableProperty(index=Index.NO,store=Store.YES)
	public Integer getWeight() {
		return weight;
	}
	public void setWeight(Integer weight) {
		this.weight = weight;
	}
	@Lob @Column(nullable=false) @SearchableProperty(store=Store.YES)
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	@Column(length=30) @SearchableProperty(index=Index.NO,store=Store.YES)
	public String getBuyexplain() {
		return buyexplain;
	}
	public void setBuyexplain(String buyexplain) {
		this.buyexplain = buyexplain;
	}
	@Column(nullable=false)
	public Boolean getVisible() {
		return visible;
	}
	public void setVisible(Boolean visible) {
		this.visible = visible;
	}
	@ManyToOne(cascade=CascadeType.REFRESH,optional=false)
	@JoinColumn(name="typeid") @SearchableComponent
	public ProductType getType() {
		return type;
	}
	public void setType(ProductType type) {
		this.type = type;
	}
	@Temporal(TemporalType.DATE) @SearchableProperty(index=Index.NO,store=Store.YES,format="yyyy-MM-dd")
	public Date getCreatedate() {
		return createdate;
	}
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}
	@Column(nullable=false)
	public Integer getClickcount() {
		return clickcount;
	}
	public void setClickcount(Integer clickcount) {
		this.clickcount = clickcount;
	}
	@Column(nullable=false)
	public Integer getSellcount() {
		return sellcount;
	}
	public void setSellcount(Integer sellcount) {
		this.sellcount = sellcount;
	}
	@Column(nullable=false)
	public Boolean getCommend() {
		return commend;
	}
	public void setCommend(Boolean commend) {
		this.commend = commend;
	}
	@Enumerated(EnumType.STRING) @Column(length=5,nullable=false) @SearchableProperty(index=Index.NO,store=Store.YES)
	public Sex getSexrequest() {
		return sexrequest;
	}
	public void setSexrequest(Sex sexrequest) {
		this.sexrequest = sexrequest;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final ProductInfo other = (ProductInfo) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
}

babasport/src/cn/itcast/bean/product/ProductStyle.java
package cn.itcast.bean.product;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Transient;

import org.compass.annotations.Index;
import org.compass.annotations.Searchable;
import org.compass.annotations.SearchableProperty;
import org.compass.annotations.SearchableReference;
import org.compass.annotations.Store;

@Entity @Searchable(root=false)
public class ProductStyle implements Serializable{
	private static final long serialVersionUID = -4926119953511144279L;
	private Integer id;
	/** 样式的名称 **/
	private String name;
	/** 图片 **/
	private String imagename;
	/** 是否可见 **/
	private Boolean visible = true;
	private ProductInfo product;
	
	public ProductStyle() {}
	
	public ProductStyle(Integer id) {
		this.id = id;
	}

	public ProductStyle(String name, String imagename) {
		this.name = name;
		this.imagename = imagename;
	}
	@ManyToOne(cascade=CascadeType.REFRESH,optional=false)
	@JoinColumn(name="productid") @SearchableReference
	public ProductInfo getProduct() {
		return product;
	}
	public void setProduct(ProductInfo product) {
		this.product = product;
	}
	@Id @GeneratedValue  @SearchableProperty(index=Index.NO, store=Store.YES)
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	@Column(length=30,nullable=false)  @SearchableProperty(index=Index.NO, store=Store.YES)
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	@Column(length=40,nullable=false) @SearchableProperty(index=Index.NO, store=Store.YES)
	public String getImagename() {
		return imagename;
	}
	public void setImagename(String imagename) {
		this.imagename = imagename;
	}
	@Column(nullable=false)
	public Boolean getVisible() {
		return visible;
	}
	public void setVisible(Boolean visible) {
		this.visible = visible;
	}
	@Transient
	public String getImageFullPath(){
		return "/images/product/"+ this.getProduct().getType().getTypeid()+ "/"+
		this.getProduct().getId()+ "/prototype/"+ this.imagename;
	}
	@Transient
	public String getImage140FullPath(){
		return "/images/product/"+ this.getProduct().getType().getTypeid()+ "/"+
		this.getProduct().getId()+ "/140x/"+ this.imagename;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final ProductStyle other = (ProductStyle) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
}

babasport/src/cn/itcast/service/product/impl/BrandServiceBean.java
package cn.itcast.service.product.impl;

import java.util.UUID;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import cn.itcast.bean.product.Brand;
import cn.itcast.service.base.DaoSupport;
import cn.itcast.service.product.BrandService;


@Service
@Transactional
public class BrandServiceBean extends DaoSupport<Brand> implements BrandService {

	@Override
	public void save(Object entity) {
		((Brand)entity).setCode(UUID.randomUUID().toString());
		super.save(entity);
	}
	
}

babasport/src/cn/itcast/service/product/impl/ProductInfoServiceBean.java
package cn.itcast.service.product.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;
import javax.persistence.Query;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import cn.itcast.bean.product.Brand;
import cn.itcast.bean.product.ProductInfo;
import cn.itcast.service.base.DaoSupport;
import cn.itcast.service.product.ProductInfoService;
import cn.itcast.service.product.ProductTypeService;


@Service
@Transactional
public class ProductInfoServiceBean extends DaoSupport<ProductInfo> implements ProductInfoService {
	@Resource(name="productTypeServiceBean") private ProductTypeService productTypeService;
	
	@SuppressWarnings("unchecked")
	@Transactional(readOnly=true,propagation=Propagation.NOT_SUPPORTED)
	public List<ProductInfo> getViewHistory(Integer[] productids, int maxResult){
		StringBuffer jpql = new StringBuffer();
		for(int i=0 ;i<productids.length; i++){
			jpql.append('?').append(i).append(',');
		}
		jpql.deleteCharAt(jpql.length()-1);
		Query query = em.createQuery("select o from ProductInfo o where o.id in("+ jpql.toString()+")");
		for(int i=0 ;i<productids.length; i++){
			query.setParameter(i, productids[i]);
		}
		query.setFirstResult(0).setMaxResults(maxResult);
		return query.getResultList();
	}
	
	@SuppressWarnings("unchecked")
	@Transactional(readOnly=true,propagation=Propagation.NOT_SUPPORTED)
	public List<ProductInfo> getTopSell(Integer typeid, int maxResult){
		List<Integer> typeids = new ArrayList<Integer>();
		typeids.add(typeid);
		getTypeids(typeids, new Integer[]{typeid});
		StringBuffer n = new StringBuffer();
		for(int i=0; i<typeids.size();i++){
			n.append('?').append((i+2)).append(',');
		}
		n.deleteCharAt(n.length()-1);
		Query query = em.createQuery("select o from ProductInfo o where o.commend=?1 and o.type.typeid in("+ n.toString()+") order by o.sellcount desc");
		query.setParameter(1, true);		
		for(int i=0; i<typeids.size();i++){
			query.setParameter(i+2, typeids.get(i));
		}
		query.setFirstResult(0).setMaxResults(maxResult);
		return query.getResultList();
	}
	
	private void getTypeids(List<Integer> outtypeids, Integer[] typeids){
		List<Integer> subtypeids = productTypeService.getSubTypeid(typeids);
		if(subtypeids!=null && subtypeids.size()>0){
			outtypeids.addAll(subtypeids);
			Integer[] ids = new Integer[subtypeids.size()];
			for(int i=0;i<subtypeids.size();i++){
				ids[i]=subtypeids.get(i);
			}
			getTypeids(outtypeids, ids);
		}
	}

	@SuppressWarnings("unchecked")
	@Transactional(readOnly=true,propagation=Propagation.NOT_SUPPORTED)
	public List<Brand> getBrandsByProductTypeid(Integer[] typeids){
		if(typeids!=null && typeids.length>0){
			StringBuffer jpql = new StringBuffer();
			for(int i=0;i<typeids.length;i++){
				jpql.append('?').append((i+1)).append(',');
			}
			jpql.deleteCharAt(jpql.length()-1);			
			Query query = em.createQuery("select o from Brand o where o.code in(select p.brand.code from ProductInfo p where p.type.typeid in("+ jpql.toString()+") group by p.brand.code)");
			for(int i=0;i<typeids.length;i++){
				query.setParameter(i+1, typeids[i]);
			}
			return query.getResultList();
		}
		return null;
	}
	
	public void setCommendStatu(Integer[] productids, boolean statu) {
		if(productids!=null && productids.length>0){
			StringBuffer jpql = new StringBuffer();
			for(int i=0;i<productids.length;i++){
				jpql.append('?').append((i+2)).append(',');
			}
			jpql.deleteCharAt(jpql.length()-1);
			Query query = em.createQuery("update ProductInfo o set o.commend=?1 where o.id in("+ jpql.toString()+ ")");
			query.setParameter(1, statu);
			for(int i=0;i<productids.length;i++){
				query.setParameter(i+2, productids[i]);
			}
			query.executeUpdate();
		}
	}

	public void setVisibleStatu(Integer[] productids, boolean statu) {
		if(productids!=null && productids.length>0){
			StringBuffer jpql = new StringBuffer();
			for(int i=0;i<productids.length;i++){
				jpql.append('?').append((i+2)).append(',');
			}
			jpql.deleteCharAt(jpql.length()-1);
			Query query = em.createQuery("update ProductInfo o set o.visible=?1 where o.id in("+ jpql.toString()+ ")");
			query.setParameter(1, statu);
			for(int i=0;i<productids.length;i++){
				query.setParameter(i+2, productids[i]);
			}
			query.executeUpdate();
		}
	}
}

babasport/src/cn/itcast/service/product/impl/ProductSearchServiceBean.java
package cn.itcast.service.product.impl;

import javax.annotation.Resource;

import org.compass.core.Compass;
import org.compass.spring.CompassDaoSupport;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import cn.itcast.bean.QueryResult;
import cn.itcast.bean.product.ProductInfo;
import cn.itcast.service.product.ProductSearchService;

@Service @Transactional
public class ProductSearchServiceBean extends CompassDaoSupport implements ProductSearchService {
	
	@Resource
	public void setSessionFactory(Compass compass){
		super.setCompass(compass);
	}
	
	public QueryResult<ProductInfo> search(String key, int startIndex, int maxResult) {
		return this.getCompassTemplate().execute(new ProductResultCallback(key, startIndex, maxResult));
	}

}

babasport/src/cn/itcast/service/product/impl/ProductStyleServiceBean.java
package cn.itcast.service.product.impl;

import javax.persistence.Query;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import cn.itcast.bean.product.ProductStyle;
import cn.itcast.service.base.DaoSupport;
import cn.itcast.service.product.ProductStyleService;


@Service
@Transactional
public class ProductStyleServiceBean extends DaoSupport<ProductStyle> implements ProductStyleService {

	public void setVisibleStatu(Integer[] productstyleids, boolean statu) {
		if(productstyleids!=null && productstyleids.length>0){
			StringBuffer jpql = new StringBuffer();
			for(int i=0;i<productstyleids.length;i++){
				jpql.append('?').append((i+2)).append(',');
			}
			jpql.deleteCharAt(jpql.length()-1);
			Query query = em.createQuery("update ProductStyle o set o.visible=?1 where o.id in("+ jpql.toString()+ ")");
			query.setParameter(1, statu);
			for(int i=0;i<productstyleids.length;i++){
				query.setParameter(i+2, productstyleids[i]);
			}
			query.executeUpdate();
		}
	}
}

babasport/WebRoot/WEB-INF/page/product/frontpage/productview.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    <%@ include file="/WEB-INF/page/share/taglib.jsp" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link href="/css/global/header01.css" rel="stylesheet" type="text/css">
<link href="/css/product/product.css" rel="stylesheet" type="text/css">
<link href="/css/global/topcommend.css" rel="stylesheet" type="text/css">
<SCRIPT language=JavaScript src="/js/FoshanRen.js"></SCRIPT>
<SCRIPT language=JavaScript src="/js/xmlhttp.js"></SCRIPT>
<title>${product.name}-巴巴运动网</title>
<meta name="Keywords" content="${product.name}">
<META name="description" content="">
  <SCRIPT LANGUAGE="JavaScript">
  <!--
	function styleEvent(styleid){
		var productImage = document.getElementById('productImage_'+ styleid);
		if(productImage){
		    var main_image = document.getElementById("main_image");
			main_image.style.background="url("+ productImage.value+") center center no-repeat";
		}
	}
	
	function bigImageBrowse(){
		var form = document.forms["cart"];
		var stypeid = form.styleid.value;
		var productPrototypeImage = document.getElementById('productPrototypeImage_'+ stypeid);		
		if(productPrototypeImage){
			var path = "<html:rewrite action="/product/switch"/>?method=showimage&path="+ productPrototypeImage.value;			
			window.open (path ,"显示图片");
		}
	}
  //-->
  </SCRIPT>
</head>

<body>
<jsp:include page="/WEB-INF/page/share/Head.jsp"/>
<div id="ContentBody"><!-- 页面主体 -->
    <c:set var="out" value="&gt;&gt; <em>${product.name}</em>"/><c:forEach items="${stypes}" var="type" varStatus="statu">
		<c:set var="out" value=" &gt;&gt; <a href='/product/list.do?typeid=${type.typeid}'>${type.name}</a> ${out}"/>
	</c:forEach>
	 	 <div id="position"> 您现在的位置：<a href="/" name="linkHome">巴巴运动网</a> <span id="uc_cat_spnPath"><c:out value="${out}" escapeXml="false"></c:out></span></div>
 <div class="browse_left"><!-- 页面主体 左边 --> 
        <!-- 浏览过的商品 -->
	 <div class="browse">
	      <div class="browse_t">您浏览过的商品</div>
	      <ul><div id="historyaccess"></div></ul>
	 </div>
	<!--精品推荐 start -->
	<DIV id="topcommend" align="left">
	       <DIV id="newtop"><IMG height=13 src="/images/global/sy2.gif" width=192></DIV>
	       <DIV id="newlist">
		  <DIV id="newmore">
		    <DIV class="title">精品推荐</DIV>
		  </DIV>
			<span id="commenddetail">
			</span>
		</DIV>
	</DIV>
</div><!-- 页面主体 左边end -->
	
 <div id="Right" ><!-- 页面主体 右边 -->
<form action="<html:rewrite action="/shopping/cart"/>" method="post" name="cart">
<INPUT TYPE="hidden" NAME="productid" value="${product.id}">
<div id="browse_left"><c:set var="currentimage"/><c:set var="imagecount" value="0"/>
<c:forEach items="${product.styles}" var="style"><c:if test="${style.visible}"><c:set var="currentimage" value="${style}"/><c:set var="imagecount" value="${imagecount+1}"/></c:if></c:forEach>
							<div class="right_left">
								<div id="main_image" onclick="JavaScript:bigImageBrowse()" style="cursor:hand;background:url(${currentimage.image140FullPath}) center center no-repeat"><img src="/images/global/product_blank.gif" WIDTH="200" HEIGHT="240"/></div>
								<img src="/images/global/zoom+.gif" onclick="JavaScript:bigImageBrowse()" style="cursor:hand;"/>
							</div>
							
							<div class="right_right">									
									<div class="right_title"><b>${product.name}</b></div>
									<div class="right_desc">
											<ul>
												<li class="li2">商品编号：A${product.id}<font color="#CC0000">（电话订购专用）</font></li>
												<c:if test="${!empty product.brand}"><li>品牌：${product.brand.name} </li>	</c:if>																																		</ul>
									</div>
									<div class="right_desc">
											<c:if test="${imagecount==1}">
											<INPUT TYPE="hidden" NAME="styleid" value="${currentimage.id }">
											<li>颜色：${currentimage.name }</li>
											<INPUT TYPE="hidden" id="productImage_${currentimage.id }" value="${currentimage.imagename}">
											<INPUT TYPE="hidden" id="productPrototypeImage_${currentimage.id }" value="${currentimage.imageFullPath}">
											</c:if>
											<c:if test="${imagecount>1}">
												<img src="/images/global/init.gif" width="0" height="0">
												<li>颜色：<SELECT name="styleid" onchange="javascript:styleEvent(this.value)">
												<c:forEach items="${product.styles}" var="style"><c:if test="${style.visible}">
												<option value="${style.id }" <c:if test="${style.id==currentimage.id}">selected </c:if>>${style.name }</option></c:if></c:forEach>
												</SELECT></li>
												<c:forEach items="${product.styles}" var="style"><c:if test="${style.visible}">
												<INPUT TYPE="hidden" id="productImage_${style.id }" value="${style.image140FullPath}">
											    <INPUT TYPE="hidden" id="productPrototypeImage_${style.id }" value="${style.imageFullPath}"></c:if></c:forEach>
											</c:if>
											  
											 </div>
									<ul>
										<li>市场价：<s>${product.marketprice}</s> 元 <font color='#ff6f02'>本站价：<b>${product.sellprice} 元</b></font> 节省：<font color='#ff6f02'>${product.savedPrice }</font> 元										</li>
									  	<li class="right_img"><INPUT TYPE="image" SRC="/images/global/sale.gif"></li>
																				<li class="guopiprice">
										[ <IMG src="/images/global/2j4.gif" border="0">&nbsp;<A href="http://www.babasport.com/cache/news/6/9.shtml" target="_blank">配送说明</A> ]&nbsp;&nbsp;&nbsp;&nbsp;[ <IMG src="/images/global/2j4.gif" border="0">&nbsp;<A href="http://www.babasport.com/cache/news/4/24.shtml" target="_blank">付款方式</A> ]
										</li>
									</ul>									
							</div>
</div>
							<div id="browse_right"><div id="sy_biankuang">
										<div class="sy_xinpintuijian_font">本站尚未开张</div>
										<div class="sy_dianhua" style="line-height:150%"><font color="#FF0000">
											全国：010-6466 3070</font><br>MSN在线客服：babasport@sohu.com<br>	
										<font color="#3A8FAF">QQ在线客服：523429525</font></div>
							</div></div>
</form>
							<div class='right_blank'></div><div class='right_title1'>商品说明</div><div class='right_content'>${product.description}</div>

 </div><!-- 页面主体 右边 end -->
</div><!-- 页面主体 end -->

<jsp:include page="/WEB-INF/page/share/Foot.jsp" />
</body>
</html>

babasport/WebRoot/WEB-INF/page/product/frontpage/showimage.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
     <%@ include file="/WEB-INF/page/share/taglib.jsp" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>显示图片</title>
</head>
<body>
<center><img src="${param.path}"/></center>
</body>
</html>

babasport/WebRoot/WEB-INF/page/product/frontpage/topsell.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/WEB-INF/page/share/taglib.jsp" %>
<UL>
	<c:forEach items="${topsellproducts}" var="topsellproduct" varStatus="statu">
		<LI class="bx">${statu.count}.<a href="<html:rewrite action="/product/view"/>?productid=${topsellproduct.id}" target="_blank" >${topsellproduct.name}</a></LI></c:forEach>			
</UL>

babasport/WebRoot/WEB-INF/page/product/frontpage/viewHistory.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/WEB-INF/page/share/taglib.jsp" %>
	<c:forEach items="${viewHistory}" var="viewproduct" varStatus="statu">
		<li class="bj_blue"><a href="<html:rewrite action="/product/view"/>?productid=${viewproduct.id}" target="_blank" title="${viewproduct.name}">${viewproduct.name}</a></li></c:forEach>			